name: build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "🚀 Starting SkillSwap CI"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show repository structure
        run: ls -R

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd server
          npm install

      - name: Run Backend Check
        run: |
          cd server
          node -e "console.log('Backend OK')"

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      - name: Build React App
        run: |
          cd client
          npm run build

      - name: Complete job
        run: echo "🎉 Build Successful"
